# Versão do Docker Compose
version: '3.8'


services:

  #Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: produtos-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=produtosdb
    volumes:
      - db-data:/var/lib/mysql


  cache:
    image: redis:7-alpine
    container_name: produtos-cache
    ports:
      - "6379:6379"


volumes:
  db-data: